{% set version = '2.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-withr
  version: {{ version|replace("-", "_") }}

source:
  fn: withr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/withr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/withr/withr_{{ version }}.tar.gz
  sha256: 36be55ca44cdf30517677f2e6e32d8bde4b581027714fb953a3d8fd19f4f9859


  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('withr')"           # [not win]
    - "\"%R%\" -e \"library('withr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/r-lib/withr#readme
  license: GPL (>= 2)
  summary: A set of functions to run code 'with' safely and temporarily modified global state.
    Many of these functions were originally a part of the 'devtools' package, this provides
    a simple package with limited dependencies to provide access to these functions.
  license_family: GPL3

extra:
  recipe-maintainers:
    - croth1
    - mingwandroid

# The original CRAN metadata for this package was:

# Encoding: UTF-8
# Package: withr
# Title: Run Code 'With' Temporarily Modified Global State
# Version: 2.0.0
# Authors@R: c( person("Jim", "Hester", , "james.f.hester@gmail.com", role = c("aut", "cre")), person("Kirill", "M<U+00FC>ller", , "krlmlr+r@mailbox.org", role = "aut"), person("Kevin", "Ushey", email = "kevinushey@gmail.com", role = c("aut")), person("Hadley", "Wickham", , "hadley@rstudio.com", role = "aut"), person("Winston", "Chang", role = "aut"), person("RStudio", role = "cph"))
# Description: A set of functions to run code 'with' safely and temporarily modified global state. Many of these functions were originally a part of the 'devtools' package, this provides a simple package with limited dependencies to provide access to these functions.
# URL: http://github.com/r-lib/withr#readme
# BugReports: http://github.com/r-lib/withr/issues
# Depends: R (>= 3.0.2)
# License: GPL (>= 2)
# LazyData: true
# Imports: stats, graphics
# Suggests: testthat
# Collate: 'local_.R' 'with_.R' 'collate.R' 'defer.R' 'dir.R' 'env.R' 'libpaths.R' 'locale.R' 'makevars.R' 'options.R' 'par.R' 'path.R' 'seed.R' 'wrap.R' 'sink.R' 'utils.R' 'with.R'
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-07-28 19:07:05 UTC; jhester
# Author: Jim Hester [aut, cre], Kirill M<U+00FC>ller [aut], Kevin Ushey [aut], Hadley Wickham [aut], Winston Chang [aut], RStudio [cph]
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-07-28 22:56:28 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
