travis:
  secure:
    BINSTAR_TOKEN: V4qLtslgDrpDY+s9zNmy8eYcb//CO6MbNbZyTNe0j45RBrmqk3TRZG+53O/WK3Y+QsaAxQBwDTAyT43Vt1rMUhgZ+xYrgl5PmlwAycFxaZg3mi00XlVWGt5FIDXPGUdBKE7zdey6tav7BK9uVdlElIo0Wfq0AdljTJjy77K3zB3EAlKm1alckYhTlLK+urkPGYIQOXlJm09ClkL54jA5Oi+LDsZW9E7A0eSRnQkj7gK9uVRRzsieNV3MwGByTshJtsOmGmi+xJPSntiG7kzcU3gsvmGvxlETVmT2Pi5e6COQbqfqIpLnOvuRKuq88e3l0uIofRBpIkq0olN6x5aKoDgGzD9Wm521njhrT+X0cfY9KBdHbkpMvDJ90KMUj7QfYOI/q3hvU33+z+to/gRUdr6v9bqIv3/o7pLvOirmfwXKxBZzFPZlqWtOejCCpJ3IgAJoRBR5QDCrrgnZrTn1RZnhoDoZuYWey6V+u78CN4LgX0lbI+yImIbeyYvLYMufRQ4c+4CfyaLSVtu7sXKCBQqHqNBIhnYTzEKxLMf3URW7POe+Q3U2ZtRpxCzyIyKH8JR5NJ/81cuqCMdDje4xkpcAJVIRiIdmW/TCn4dw2mZcv7OHtJRqCcRHBCvy2/g1gIA87GmkZOMEH1ySYNVB6ME3/65Cdh6OAl7p7eFoapc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
