travis:
  secure:
    BINSTAR_TOKEN: diFwQqrxU786JGui5Jcy0vRFdrihw0ItImWcHNgi0R8jJs3hNgyOe2DKncEQFurPbg7aJCLcT2kwIOdg/1leO+kCkjaeO01KRr7qvCHMpKkTaQ+I2zaaf1Sq8ibmiAPToFzTBeAJuYgznvq0bJZC6mT29xcBLTwIY9etXakLyHZur4gDHhUfPOKaClwb7JTiy07cR5/SgpwZ4PXCqeIUG5WDQ6kga2Y7S3A94p3o+ZG7dZ59FTWvApoK37/Oz5CaQlfZ+7+GYWhN6uVyrcEcxUdnco3Z1eCZq36a6GhnQ3CHR3JKnNjTQXpAgBLtIy773WjTlCR5Exyn6TAai8ecyrSD5qxpuwWVBuXFg1OcFHv0oBKYImGeSB79RXMZDTfR+HEULAfhQNG5htCuMPTTs3/Zo8DNiWjLERoRXHZLbHza5lZIfGfdZUXiTex8N5gvJ/o7s8iYoAX+1ARLPnBrRIU38eSKB9GvJrvrlG9bfjk+pxLbEnFl+1mohswxoSTUqraQP+t6T9YS4wTBBJlWirKTl7ard2Wu+p6in3O2y25rk/cP+vrb9spdeXI+xmUT1qHTeOYZS7r+ZD65Fash1sFqGpQKIqnbMMImp9fJeOYWXa6DEYMWjTzU5ggUZL84zKXk5UBwl0A6mRZp+tb0j/21oNgeiAOB1OiKz5EexOc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
