travis:
  secure:
    BINSTAR_TOKEN: wAVhPVNpxmBFYE11wc/Y+E1gMBgVrbFWV0O6sS+YBzHJ8zlL0Avy5gSLVmKtVdO7eirVi0F6eVis3Z+sj6d8QQ1n8bvUejZOHPmGcBJCM36OFz3sI0HYQeRrYP2GwDNipola3LCcef6xBx+sipSmdD8y9FUnQ0vINhH9K3wEzNPDJiGbW5FUrJe9ljm6aJ1cO54cCGKeUo+yVjKRIkVlUbiui5xsp4rXqQxZbR1v0UoeqRUDD/XmJORP31mISy0LYcV0GIXJfj4nvecQEc6HFSG0mCqSKgba4n5kZDODlaTU9ClIsxynBs58Gl+wXuyVUWFsN+0USK7L4MGbjOOBBzX2eG7QpxbaJZNnNpZTWADdxEe3MzZq+d8SEfotmkI36Fc0Pbp1QgOTTsC6sGsvUljb4iHRWchhWR2v4/I/F8SaGu8d66Eh4qGdq/gs5J7NnCvYVB7sAAk7ZRSBiC3aASZ/2+7r/oQOOOWqaUY/MtrlCIBpEdWB6AyZqyq9Muy3W5TKKzcDlU8cRuP5tD8kw78acr44Ot3aaa3bJNLdQYPKHnDMA2FwnLkJT21Mz2t5jy2Uwgl5FJeRgTGdiU2IIKePjwzfdgw0120nLaF2awyFE9lODxkVJxw0oiWCJZUbnzgBsoFSUaRlC9nEmJVsUkmyiF/fvErvMnZEL5UP50Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
