travis:
  secure:
    BINSTAR_TOKEN: DgoYYEFc/WzRODIXrcyasG59vbw0l/orhsuKOgaQ+7v+vyTXrUwlTEm+iOCYhdXt/zhljr2dGtvu0jIPFBH8RjnRaAwXRHpCj1Xd6y6vj3fDsn8ZJQosaZ2ArhkG5xY6/Ab0YBrKRvpy5kKHNtCSknjAXAup6Z0op2oTtRnUf+8bJIflvLRvFaXK4H85PwL2qEovtJdQPN+dVyyKig4HrzPivpPV0vW3naJ//D2JV0UHl9GW4PyC5tLRW0hjsLrJHyse6+NL6N3v3oIaYzsGQ7QfPwOx1AyfktqnB7hAMEeFxXFJDl/gY9QL+NxrFJ/Ty6kWAB7K1tajWTMsqI21GJwMlOGqwnyahQBee902/ls/lpqor91lzMUoWW4XZvf8UvrqQgcNdAf/glV8itbGXzEAORH2/xsFBZ1R4dODLYNEFaCaEiz3G94dfDwfkBiAuWjrFX0i/aM3+drCaA02rSnwRzv69+pF1Oj3AU+GWZ75Rd4kvaaE+45iKGwts7UMUT3swUSAmzFmDRYCj4cuGc2RJrJZaeoBDUqOMFOtQxnnogWan0Ff7vUN/tnA4HnfPCq+DR0d5CrVchYdEjSacDLXSdAkI5vxU8GU2dIhf+ksNAnmTH+utp6cj8ABBPvSBZPU01T0biJ02Vj0/E440d5jmpUK9IomxWZFCx6T6Ew=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
